import { motion } from "framer-motion";
import { useMemo, useState } from "react";
import { Wallet, CheckCircle2, AlertTriangle, Download, Receipt, CreditCard } from "lucide-react";
import PageHeader from "../../components/common/PageHeader";
import { Skeleton } from "../../components/common/Skeleton";
import ErrorState from "../../components/common/ErrorState";
import EmptyState from "../../components/common/EmptyState";
import useApi from "../../hooks/useApi";
import api from "../../services/api";
import { fileUrl } from "../../services/api";
import { useToast } from "../../context/ToastContext";

const fmtMoney = (n) => `Rs. ${Number(n || 0).toLocaleString("en-PK")}`;
const fmtDate = (d) => {
  if (!d) return "—";
  try {
    return new Date(d).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" });
  } catch {
    return d;
  }
};

const statusChip = (s) => {
  const v = (s || "").toUpperCase();
  if (v === "PAID") return "bg-emerald-100 text-emerald-700";
  if (v === "OVERDUE") return "bg-rose-100 text-rose-700";
  if (v === "PARTIAL") return "bg-amber-100 text-amber-700";
  return "bg-slate-100 text-slate-600";
};

const safeItems = (li) => {
  if (Array.isArray(li)) return li;
  if (typeof li === "string") {
    try { const p = JSON.parse(li); return Array.isArray(p) ? p : []; } catch { return []; }
  }
  return [];
};

const AccountBook = () => {
  const { toast } = useToast();
  const { data, loading, error, reload } = useApi(() => api.student.fees(), []);
  const [paying, setPaying] = useState(null);

  const challans = useMemo(() => data?.challans || [], [data]);
  const summary = data?.summary || { total: 0, paid: 0, outstanding: 0 };

  const payNow = async (ch) => {
    setPaying(ch.id);
    try {
      await api.student.payFee(ch.id, { method: "OneLink" });
      toast(`Payment successful — ${ch.title} marked as Paid`, { type: "success" });
      reload();
    } catch (e) {
      toast(e.message || "Payment failed", { type: "error" });
    } finally {
      setPaying(null);
    }
  };

  if (loading) {
    return (
      <div>
        <PageHeader title="Accounts Book" subtitle="Fee challans, payments, and dues" icon="Wallet" breadcrumb={["Dashboard", "Accounts Book"]} />
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3 mb-5">{Array.from({ length: 3 }).map((_, i) => <Skeleton key={i} className="h-28 rounded-2xl" />)}</div>
        <Skeleton className="h-64 rounded-2xl" />
      </div>
    );
  }

  return (
    <div>
      <PageHeader title="Accounts Book" subtitle="Fee challans, payments, and dues" icon="Wallet" breadcrumb={["Dashboard", "Accounts Book"]} />

      {error ? (
        <ErrorState description={error} onRetry={reload} />
      ) : challans.length === 0 ? (
        <EmptyState icon="Wallet" title="No fee records" description="Your fee challans and payment history will appear here once generated by the finance office." />
      ) : (
        <>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-3 mb-5">
            {[
              { label: "Total Billed", value: fmtMoney(summary.total), color: "from-blue-500 to-indigo-600", icon: Wallet },
              { label: "Total Paid", value: fmtMoney(summary.paid), color: "from-emerald-500 to-teal-600", icon: CheckCircle2 },
              { label: "Outstanding", value: fmtMoney(summary.outstanding), color: "from-rose-500 to-pink-600", icon: AlertTriangle },
            ].map((s, i) => (
              <motion.div key={s.label} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.05 }} className={`relative bg-gradient-to-br ${s.color} rounded-2xl p-5 text-white overflow-hidden`}>
                <div className="absolute -right-2 -top-2 w-20 h-20 bg-white/10 rounded-full blur-xl" />
                <s.icon size={22} className="mb-2" />
                <p className="font-display text-2xl font-extrabold">{s.value}</p>
                <p className="text-xs opacity-90">{s.label}</p>
              </motion.div>
            ))}
          </div>

          <div className="space-y-4">
            {challans.map((ch, i) => {
              const items = safeItems(ch.lineItems);
              return (
                <motion.div key={ch.id} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.05 }} className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-100 dark:border-slate-800 overflow-hidden">
                  <div className="px-5 py-4 border-b border-slate-100 dark:border-slate-800 flex items-center justify-between flex-wrap gap-2">
                    <div className="flex items-center gap-3">
                      <div className="p-2 rounded-xl bg-primary-50 dark:bg-primary-900/30"><Receipt size={20} className="text-primary-600" /></div>
                      <div>
                        <p className="font-display font-bold text-slate-900 dark:text-slate-100 flex items-center gap-2">
                          {ch.title}
                          {ch.source === "admission" && (
                            <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-indigo-100 text-indigo-700 dark:bg-indigo-900/40 dark:text-indigo-300">ADMISSION</span>
                          )}
                        </p>
                        <p className="text-xs text-slate-500 dark:text-slate-400">Challan #{ch.challanNo}{ch.source === "admission" ? "" : ` · Due ${fmtDate(ch.dueDate)}`}</p>
                      </div>
                    </div>
                    <span className={`text-xs font-bold px-3 py-1 rounded-full ${statusChip(ch.status)}`}>{ch.status}</span>
                  </div>
                  {items.length > 0 && (
                    <div className="px-5 py-3">
                      <table className="w-full text-sm">
                        <tbody>
                          {items.map((it, j) => (
                            <tr key={j} className="border-b border-slate-50 dark:border-slate-800/50 last:border-0">
                              <td className="py-1.5 text-slate-700 dark:text-slate-300">{it.label || it.name || it.description}</td>
                              <td className="py-1.5 text-right font-semibold text-slate-900 dark:text-slate-100">{fmtMoney(it.amount)}</td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                  )}
                  <div className="px-5 py-3 bg-slate-50 dark:bg-slate-900/50 flex items-center justify-between flex-wrap gap-2">
                    <div className="text-sm">
                      <span className="text-slate-500 dark:text-slate-400">Total: </span>
                      <span className="font-display font-extrabold text-lg text-slate-900 dark:text-slate-100">{fmtMoney(ch.totalAmount)}</span>
                      {ch.status === "PAID" && ch.paidAt && (
                        <span className="ml-3 text-xs text-emerald-600 font-semibold">Paid {fmtDate(ch.paidAt)}{ch.paymentRef ? ` · Ref ${ch.paymentRef}` : ""}</span>
                      )}
                    </div>
                    <div className="flex items-center gap-2">
                      {ch.fileName && (
                        <a href={fileUrl(ch.fileName)} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 text-xs font-semibold px-3 py-1.5 rounded-lg bg-slate-200 dark:bg-slate-700 text-slate-700 dark:text-slate-200 hover:bg-slate-300 dark:hover:bg-slate-600">
                          <Download size={14} /> Download Challan
                        </a>
                      )}
                      {ch.status !== "PAID" && ch.status !== "WAIVED" && (
                        <button onClick={() => payNow(ch)} disabled={paying === ch.id}
                          className="inline-flex items-center gap-1.5 text-xs font-semibold px-4 py-1.5 rounded-lg bg-emerald-600 text-white hover:bg-emerald-700 disabled:opacity-50">
                          <CreditCard size={14} /> {paying === ch.id ? "Processing…" : "Pay Now"}
                        </button>
                      )}
                    </div>
                  </div>
                </motion.div>
              );
            })}
          </div>
        </>
      )}
    </div>
  );
};

export default AccountBook;
