// ============================================================
//  SUPER ADMIN — CLIENT-SIDE EXPORTERS (CSV / Excel / PDF)
//  ------------------------------------------------------------
//  Zero-dependency exporters that work entirely in the browser:
//   - CSV:   standard comma-separated, quoted as needed
//   - Excel: SpreadsheetML (.xls) HTML-table format Excel opens natively
//   - PDF:   opens a print-ready window → user's "Save as PDF"
//  Used by DataTable + report pages so every table can export to all
//  three formats as required by the enhancement spec.
// ============================================================

function esc(v) {
  if (v == null) return '';
  const s = String(v);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

function valueFor(col, row) {
  if (col.exportValue) return col.exportValue(row);
  return row[col.key];
}

export function exportCsv(columns, rows, name = 'export') {
  const cols = columns.filter((c) => c.key !== '__actions' && c.exportable !== false);
  const header = cols.map((c) => c.header).join(',');
  const body = rows.map((r) => cols.map((c) => esc(valueFor(c, r))).join(',')).join('\n');
  download(`${header}\n${body}`, `${name}-${stamp()}.csv`, 'text/csv;charset=utf-8');
}

export function exportExcel(columns, rows, name = 'export', title) {
  const cols = columns.filter((c) => c.key !== '__actions' && c.exportable !== false);
  const escHtml = (v) => String(v ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const head = `<tr>${cols.map((c) => `<th style="background:#1e3a5f;color:#fff;border:1px solid #ccc;padding:6px;text-align:left">${escHtml(c.header)}</th>`).join('')}</tr>`;
  const body = rows.map((r) =>
    `<tr>${cols.map((c) => `<td style="border:1px solid #ccc;padding:6px">${escHtml(valueFor(c, r))}</td>`).join('')}</tr>`
  ).join('');
  const html = `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
  <head><meta charset="utf-8"></head>
  <body>${title ? `<h3>${escHtml(title)}</h3>` : ''}<table>${head}${body}</table></body></html>`;
  download(html, `${name}-${stamp()}.xls`, 'application/vnd.ms-excel');
}

export function exportPdf(columns, rows, name = 'export', title) {
  const cols = columns.filter((c) => c.key !== '__actions' && c.exportable !== false);
  const escHtml = (v) => String(v ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const head = `<tr>${cols.map((c) => `<th>${escHtml(c.header)}</th>`).join('')}</tr>`;
  const body = rows.map((r) =>
    `<tr>${cols.map((c) => `<td>${escHtml(valueFor(c, r))}</td>`).join('')}</tr>`
  ).join('');
  const win = window.open('', '_blank');
  if (!win) return;
  win.document.write(`<!DOCTYPE html><html><head><meta charset="utf-8"><title>${escHtml(title || name)}</title>
  <style>
    *{font-family:'Segoe UI',Arial,sans-serif}
    body{padding:28px;color:#1f2937}
    h2{color:#1e3a5f;margin:0 0 4px}
    .meta{color:#6b7280;font-size:12px;margin-bottom:18px}
    table{width:100%;border-collapse:collapse;font-size:11.5px}
    th{background:#1e3a5f;color:#fff;text-align:left;padding:7px 9px}
    td{border-bottom:1px solid #e5e7eb;padding:6px 9px}
    tr:nth-child(even) td{background:#f8fafc}
    .foot{margin-top:22px;color:#9ca3af;font-size:10.5px;text-align:center}
    @media print{.noprint{display:none}}
  </style></head>
  <body>
    <h2>${escHtml(title || name)}</h2>
    <div class="meta">AUST ODL University ERP — Super Admin Report · Generated ${new Date().toLocaleString()}</div>
    <button class="noprint" onclick="window.print()" style="margin-bottom:16px;padding:8px 16px;background:#1e3a5f;color:#fff;border:0;border-radius:6px;cursor:pointer">Print / Save as PDF</button>
    <table><thead>${head}</thead><tbody>${body}</tbody></table>
    <div class="foot">Confidential — Generated by AUST ODL Super Admin Console</div>
    <script>setTimeout(function(){window.print()},400)<\/script>
  </body></html>`);
  win.document.close();
}

function download(content, filename, mime) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click(); a.remove();
  URL.revokeObjectURL(url);
}

function stamp() {
  return new Date().toISOString().slice(0, 10);
}
