import { useEffect, useMemo, useState } from "react";
import { motion } from "framer-motion";
import { FileSpreadsheet, Plus, Wand2, Trash2, Send, ChevronDown, ChevronRight, Lock, ShieldCheck, ShieldAlert, Pencil, X, Check, Loader2 } from "lucide-react";
import PageHeader from "../../components/common/PageHeader";
import StatCard from "../../components/common/StatCard";
import StatusBadge from "../../components/common/StatusBadge";
import Modal from "../../components/common/Modal";
import useApi from "../../hooks/useApi";
import api from "../../services/api";
import { Skeleton } from "../../components/common/Skeleton";
import ErrorState from "../../components/common/ErrorState";
import EmptyState from "../../components/common/EmptyState";
import { useToast } from "../../context/ToastContext";
import CascadeFilters, { emptyCascade, applyCascade } from "../../components/common/CascadeFilters";

const EXAM_TYPES = ["MID", "FINAL", "QUIZ", "RETAKE", "SPECIAL"];

const emptyEntry = () => ({ courseCode: "", courseTitle: "", section: "", date: "", startTime: "", endTime: "" });

const ExamDatesheets = () => {
  const { toast } = useToast();
  const { data, loading, error, reload } = useApi(() => api.exam.datesheets(), []);
  const { data: filterData } = useApi(() => api.exam.filters(), []);
  const allDatesheets = useMemo(() => data?.datesheets || [], [data]);

  const programs = filterData?.programs || [];
  const semByProgram = filterData?.semestersByProgram || {};

  // 1.2 — reusable cascading smart filter (dept → program → semester + session/batch).
  const [cascade, setCascade] = useState(emptyCascade());
  const datesheets = useMemo(() => applyCascade(allDatesheets, cascade, (d) => ({
    department: d.department,
    program: d.programShortForm || d.program,
    semester: d.semester,
  })), [allDatesheets, cascade]);

  const [busy, setBusy] = useState(false);
  const [expanded, setExpanded] = useState({});
  const [showAuto, setShowAuto] = useState(false);
  const [showManual, setShowManual] = useState(false);

  // Per-sheet clash-check results { [id]: { hasClash, clashes } } + loading set.
  const [clashInfo, setClashInfo] = useState({});
  const [clashLoading, setClashLoading] = useState({});

  // Inline entry editing: { sheetId, entryId } + draft.
  const [editing, setEditing] = useState(null); // { sheetId, entryId }
  const [draft, setDraft] = useState(emptyEntry());

  // Auto-generate form
  const [auto, setAuto] = useState({
    examType: "FINAL", program: "", startDate: "", durationMin: 180, gapDays: 1, slotsPerDay: 2,
    semesterMode: "ALL", semesters: [],
  });

  // Manual form
  const [manual, setManual] = useState({ title: "", examType: "FINAL", program: "", semester: "" });
  const [manualEntries, setManualEntries] = useState([emptyEntry()]);

  useEffect(() => {
    if (programs.length && !auto.program) setAuto((a) => ({ ...a, program: programs[0].shortForm || programs[0].code }));
  }, [programs]); // eslint-disable-line

  const semOptions = useMemo(() => semByProgram[auto.program] || [], [semByProgram, auto.program]);

  const stats = useMemo(() => ({
    total: datesheets.length,
    locked: datesheets.filter((d) => d.status === "LOCKED").length,
    draft: datesheets.filter((d) => d.status === "DRAFT").length,
    generated: datesheets.filter((d) => d.generated).length,
  }), [datesheets]);

  const toggleSemester = (val) => {
    setAuto((a) => {
      const has = a.semesters.includes(val);
      return { ...a, semesters: has ? a.semesters.filter((s) => s !== val) : [...a.semesters, val] };
    });
  };

  const runAutoGenerate = async () => {
    if (!auto.program || !auto.startDate) { toast?.("Program and start date are required", { type: "warning" }); return; }
    let semesters = "ALL";
    if (auto.semesterMode === "ONE") semesters = auto.semesters.slice(0, 1);
    else if (auto.semesterMode === "MULTI") semesters = auto.semesters;
    if ((auto.semesterMode === "ONE" || auto.semesterMode === "MULTI") && (!Array.isArray(semesters) || semesters.length === 0)) {
      toast?.("Select at least one semester", { type: "warning" }); return;
    }
    setBusy(true);
    try {
      const res = await api.exam.autoGenerateDatesheet({
        examType: auto.examType, program: auto.program, startDate: auto.startDate,
        durationMin: Number(auto.durationMin), gapDays: Number(auto.gapDays),
        slotsPerDay: Number(auto.slotsPerDay), semesters,
      });
      toast?.(`Generated ${res.count} date sheet(s)`, { type: "success" });
      setShowAuto(false);
      reload();
    } catch (e) { toast?.(e?.message || "Failed to generate", { type: "error" }); }
    finally { setBusy(false); }
  };

  const addManualRow = () => setManualEntries((rows) => [...rows, emptyEntry()]);
  const removeManualRow = (i) => setManualEntries((rows) => rows.filter((_, idx) => idx !== i));
  const updateManualRow = (i, key, val) => setManualEntries((rows) => rows.map((r, idx) => idx === i ? { ...r, [key]: val } : r));

  const saveManual = async () => {
    if (!manual.title.trim()) { toast?.("Title is required", { type: "warning" }); return; }
    const entries = manualEntries.filter((e) => e.date);
    if (!entries.length) { toast?.("Add at least one entry with a date", { type: "warning" }); return; }
    setBusy(true);
    try {
      const prog = programs.find((p) => (p.shortForm || p.code) === manual.program);
      await api.exam.createDatesheet({
        title: manual.title, examType: manual.examType,
        program: prog?.name || null, programShortForm: manual.program || null,
        semester: manual.semester || null, entries,
      });
      toast?.("Date sheet saved", { type: "success" });
      setShowManual(false);
      setManual({ title: "", examType: "FINAL", program: "", semester: "" });
      setManualEntries([emptyEntry()]);
      reload();
    } catch (e) { toast?.(e?.message || "Failed to save", { type: "error" }); }
    finally { setBusy(false); }
  };

  const publish = async (id) => {
    setBusy(true);
    try { await api.exam.setDatesheetStatus(id, { status: "PUBLISHED" }); toast?.("Date sheet published", { type: "success" }); reload(); }
    catch (e) { toast?.(e?.message || "Failed", { type: "error" }); } finally { setBusy(false); }
  };
  const remove = async (id) => {
    if (!confirm("Delete this date sheet?")) return;
    setBusy(true);
    try { await api.exam.deleteDatesheet(id); toast?.("Deleted", { type: "success" }); reload(); }
    catch (e) { toast?.(e?.message || "Failed", { type: "error" }); } finally { setBusy(false); }
  };

  // §1.2 — Lock finalizes the date sheet and auto-distributes a
  // personalized date sheet to every affected student and teacher.
  const lock = async (id) => {
    if (!confirm("Lock this date sheet? It will be finalized and each student & teacher will receive their own personalized date sheet. This cannot be undone.")) return;
    setBusy(true);
    try {
      const r = await api.exam.lockDatesheet(id);
      const d = r?.distributed || {};
      toast?.(`Locked & distributed to ${d.students || 0} student(s) and ${d.teachers || 0} teacher(s)`, { type: "success" });
      reload();
    } catch (e) { toast?.(e?.message || "Failed to lock", { type: "error" }); } finally { setBusy(false); }
  };

  // §1.2 — clash check per sheet (verify clash-free before locking).
  const checkClash = async (id) => {
    setClashLoading((s) => ({ ...s, [id]: true }));
    try {
      const r = await api.exam.datesheetClashCheck(id);
      setClashInfo((s) => ({ ...s, [id]: r }));
      toast?.(r.hasClash ? `${r.clashes.length} scheduling clash(es) found` : "No scheduling clashes — safe to lock", { type: r.hasClash ? "warning" : "success" });
    } catch (e) { toast?.(e?.message || "Clash check failed", { type: "error" }); }
    finally { setClashLoading((s) => ({ ...s, [id]: false })); }
  };

  // §1.2 — inline manual entry editing / deleting (DRAFT/PUBLISHED only, not LOCKED).
  const startEdit = (sheetId, e) => {
    setEditing({ sheetId, entryId: e.id });
    setDraft({ courseCode: e.courseCode || "", courseTitle: e.courseTitle || "", section: e.section || "", date: e.date || "", startTime: e.startTime || "", endTime: e.endTime || "" });
  };
  const cancelEdit = () => { setEditing(null); setDraft(emptyEntry()); };
  const saveEdit = async () => {
    if (!editing) return;
    if (!draft.date) { toast?.("Date is required", { type: "warning" }); return; }
    setBusy(true);
    try {
      await api.exam.updateDatesheetEntry(editing.sheetId, editing.entryId, draft);
      toast?.("Entry updated", { type: "success" });
      cancelEdit();
      setClashInfo((s) => { const n = { ...s }; delete n[editing.sheetId]; return n; }); // invalidate stale clash result
      reload();
    } catch (e) { toast?.(e?.message || "Failed to update entry", { type: "error" }); } finally { setBusy(false); }
  };
  const deleteEntry = async (sheetId, entryId) => {
    if (!confirm("Delete this exam slot?")) return;
    setBusy(true);
    try {
      await api.exam.deleteDatesheetEntry(sheetId, entryId);
      toast?.("Slot deleted", { type: "success" });
      setClashInfo((s) => { const n = { ...s }; delete n[sheetId]; return n; });
      reload();
    } catch (e) { toast?.(e?.message || "Failed to delete slot", { type: "error" }); } finally { setBusy(false); }
  };

  const manualSemOptions = semByProgram[manual.program] || [];

  return (
    <div>
      <PageHeader
        title="Date Sheets"
        subtitle="Auto-generate or manually build examination date sheets — saved live to the database."
        icon="FileText"
        breadcrumb={["Exam Controller", "Date Sheets"]}
        actions={
          <div className="flex gap-2">
            <button onClick={() => setShowAuto(true)} className="btn-primary text-sm py-2 px-3 flex items-center gap-2"><Wand2 size={14} /> Auto Generate</button>
            <button onClick={() => setShowManual(true)} className="btn-secondary text-sm py-2 px-3 flex items-center gap-2"><Plus size={14} /> Manual</button>
          </div>
        }
      />

      {error ? <ErrorState message={error} onRetry={reload} /> : loading ? <Skeleton className="h-96" /> : (
        <>
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mb-4">
            <StatCard title="Date Sheets" value={stats.total} icon="FileText" color="blue" />
            <StatCard title="Locked & Distributed" value={stats.locked} icon="Lock" color="emerald" delay={0.05} />
            <StatCard title="Draft" value={stats.draft} icon="Edit3" color="amber" delay={0.1} />
            <StatCard title="Auto-Generated" value={stats.generated} icon="Wand2" color="violet" delay={0.15} />
          </div>

          {/* 1.2 — reusable cascading smart filters */}
          <CascadeFilters
            className="mb-4"
            value={cascade}
            onChange={setCascade}
            fields={["department", "program", "semester"]}
            extraRows={allDatesheets}
            rowMap={(d) => ({ department: d.department })}
          />

          <div className="space-y-3">
            {datesheets.length === 0 ? <div className="card-base"><EmptyState message={allDatesheets.length ? "No date sheets match the current filters." : "No date sheets yet. Use Auto Generate or Manual to create one."} /></div> :
              datesheets.map((d, i) => {
                const ci = clashInfo[d.id];
                const isLocked = d.status === "LOCKED";
                return (
                <motion.div key={d.id} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: Math.min(i * 0.03, 0.3) }} className="card-base overflow-hidden">
                  <div className="p-4 flex items-center justify-between gap-3 flex-wrap">
                    <button onClick={() => setExpanded((e) => ({ ...e, [d.id]: !e[d.id] }))} className="flex items-center gap-2 text-left min-w-0">
                      {expanded[d.id] ? <ChevronDown size={16} /> : <ChevronRight size={16} />}
                      <FileSpreadsheet size={18} className="text-blue-500 shrink-0" />
                      <div className="min-w-0">
                        <p className="font-bold text-app text-sm truncate">{d.title}</p>
                        <p className="text-xs text-muted-app flex flex-wrap items-center gap-1">
                          <span>{d.examType} · {d.entryCount} exam slot(s){d.generated ? " · auto" : " · manual"}</span>
                          {d.programShortForm ? <span className="text-[10px] px-1.5 py-0.5 rounded-full bg-blue-50 text-blue-700 border border-blue-200 dark:bg-blue-950/40 dark:text-blue-300 dark:border-blue-900/60 font-semibold">{d.programShortForm}</span> : null}
                          {d.semester ? <span className="text-[10px] px-1.5 py-0.5 rounded-full surface border border-app font-semibold">Sem {d.semester}</span> : null}
                          {d.department ? <span className="text-[10px] px-1.5 py-0.5 rounded-full bg-violet-50 text-violet-700 border border-violet-200 dark:bg-violet-950/40 dark:text-violet-300 dark:border-violet-900/60 font-semibold">{d.department}</span> : null}
                        </p>
                      </div>
                    </button>
                    <div className="flex items-center gap-2 flex-wrap">
                      {ci && (
                        <span className={`inline-flex items-center gap-1 text-[10px] font-bold px-2 py-1 rounded-full ${ci.hasClash ? "bg-rose-100 text-rose-700 dark:bg-rose-950/40 dark:text-rose-300" : "bg-emerald-100 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300"}`}>
                          {ci.hasClash ? <ShieldAlert size={11} /> : <ShieldCheck size={11} />}
                          {ci.hasClash ? `${ci.clashes.length} clash` : "Clash-free"}
                        </span>
                      )}
                      <StatusBadge status={d.status} />
                      {!isLocked && (
                        <button disabled={clashLoading[d.id]} onClick={() => checkClash(d.id)} className="p-1.5 rounded-lg hover:bg-blue-50 text-blue-600 disabled:opacity-50" title="Check for scheduling clashes">
                          {clashLoading[d.id] ? <Loader2 size={14} className="animate-spin" /> : <ShieldCheck size={14} />}
                        </button>
                      )}
                      {d.status === "DRAFT" && <button disabled={busy} onClick={() => publish(d.id)} className="p-1.5 rounded-lg hover:bg-emerald-50 text-emerald-600" title="Publish"><Send size={14} /></button>}
                      {!isLocked && <button disabled={busy} onClick={() => lock(d.id)} className="p-1.5 rounded-lg hover:bg-violet-50 text-violet-600" title="Lock & distribute personalized date sheets"><Lock size={14} /></button>}
                      {isLocked && <span className="inline-flex items-center gap-1 text-[10px] font-bold px-2 py-1 rounded-full bg-violet-100 text-violet-700 dark:bg-violet-950/40 dark:text-violet-300"><Lock size={11} /> Distributed</span>}
                      <button disabled={busy || isLocked} onClick={() => remove(d.id)} className="p-1.5 rounded-lg hover:bg-rose-50 text-rose-600 disabled:opacity-40" title="Delete"><Trash2 size={14} /></button>
                    </div>
                  </div>

                  {/* clash detail banner */}
                  {ci?.hasClash && expanded[d.id] && (
                    <div className="px-4 pb-2">
                      <div className="rounded-lg border border-rose-200 dark:border-rose-900/60 bg-rose-50 dark:bg-rose-950/30 p-2.5 text-[11px] text-rose-700 dark:text-rose-300">
                        <p className="font-bold mb-1 inline-flex items-center gap-1"><ShieldAlert size={12} /> Scheduling clashes — resolve before locking:</p>
                        <ul className="list-disc pl-4 space-y-0.5">
                          {ci.clashes.map((c, idx) => (
                            <li key={idx}>{c.a.course || "—"} ↔ {c.b.course || "—"} on {c.date}</li>
                          ))}
                        </ul>
                      </div>
                    </div>
                  )}

                  {expanded[d.id] && (
                    <div className="border-t border-app overflow-x-auto">
                      {d.entries.length === 0 ? <EmptyState message="No slots in this date sheet." /> : (
                        <table className="w-full text-sm">
                          <thead className="surface border-b border-app"><tr>
                            {["Course", "Semester", "Section", "Date", "Time", isLocked ? null : "Actions"].filter(Boolean).map((h) => <th key={h} className="px-4 py-2 text-left text-[10px] font-bold uppercase text-muted-app">{h}</th>)}
                          </tr></thead>
                          <tbody className="divide-y divide-app">
                            {d.entries.map((e) => {
                              const isEditing = editing && editing.sheetId === d.id && editing.entryId === e.id;
                              if (isEditing) {
                                return (
                                  <tr key={e.id} className="bg-blue-50/50 dark:bg-blue-950/20">
                                    <td className="px-2 py-1">
                                      <div className="flex gap-1">
                                        <input value={draft.courseCode} onChange={(ev) => setDraft({ ...draft, courseCode: ev.target.value })} placeholder="Code" className="input-base text-xs w-20" />
                                        <input value={draft.courseTitle} onChange={(ev) => setDraft({ ...draft, courseTitle: ev.target.value })} placeholder="Title" className="input-base text-xs w-28" />
                                      </div>
                                    </td>
                                    <td className="px-2 py-1"><span className="text-xs text-muted-app">{e.semester || "—"}</span></td>
                                    <td className="px-2 py-1"><input value={draft.section} onChange={(ev) => setDraft({ ...draft, section: ev.target.value })} className="input-base text-xs w-16" /></td>
                                    <td className="px-2 py-1"><input type="date" value={draft.date} onChange={(ev) => setDraft({ ...draft, date: ev.target.value })} className="input-base text-xs w-32" /></td>
                                    <td className="px-2 py-1">
                                      <div className="flex gap-1">
                                        <input type="time" value={draft.startTime} onChange={(ev) => setDraft({ ...draft, startTime: ev.target.value })} className="input-base text-xs w-24" />
                                        <input type="time" value={draft.endTime} onChange={(ev) => setDraft({ ...draft, endTime: ev.target.value })} className="input-base text-xs w-24" />
                                      </div>
                                    </td>
                                    <td className="px-2 py-1">
                                      <div className="flex gap-1">
                                        <button disabled={busy} onClick={saveEdit} className="p-1 rounded text-emerald-600 hover:bg-emerald-50" title="Save"><Check size={14} /></button>
                                        <button onClick={cancelEdit} className="p-1 rounded text-slate-500 hover:bg-slate-100" title="Cancel"><X size={14} /></button>
                                      </div>
                                    </td>
                                  </tr>
                                );
                              }
                              return (
                                <tr key={e.id} className="hover:surface">
                                  <td className="px-4 py-2 text-xs font-semibold text-app">{e.courseCode ? `${e.courseCode} ${e.courseTitle || ""}` : (e.courseTitle || "—")}</td>
                                  <td className="px-4 py-2 text-xs text-app">{e.semester || "—"}</td>
                                  <td className="px-4 py-2 text-xs text-app">{e.section || "—"}</td>
                                  <td className="px-4 py-2 text-xs text-app">{e.date}</td>
                                  <td className="px-4 py-2 text-xs text-muted-app">{e.startTime || "—"}{e.endTime ? `–${e.endTime}` : ""}</td>
                                  {!isLocked && (
                                    <td className="px-4 py-2">
                                      <div className="flex gap-1">
                                        <button disabled={busy} onClick={() => startEdit(d.id, e)} className="p-1 rounded text-blue-600 hover:bg-blue-50" title="Edit slot"><Pencil size={13} /></button>
                                        <button disabled={busy} onClick={() => deleteEntry(d.id, e.id)} className="p-1 rounded text-rose-600 hover:bg-rose-50" title="Delete slot"><Trash2 size={13} /></button>
                                      </div>
                                    </td>
                                  )}
                                </tr>
                              );
                            })}
                          </tbody>
                        </table>
                      )}
                    </div>
                  )}
                </motion.div>
              );})}
          </div>
        </>
      )}

      {/* AUTO GENERATE MODAL */}
      <Modal open={showAuto} onClose={() => setShowAuto(false)} title="Auto Generate Date Sheet" icon="Wand2" maxWidth="max-w-lg">
        <div className="space-y-3">
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="text-[10px] uppercase font-bold text-muted-app mb-1 block">Exam Type</label>
              <select value={auto.examType} onChange={(e) => setAuto({ ...auto, examType: e.target.value })} className="input-base w-full text-sm">
                {EXAM_TYPES.map((t) => <option key={t} value={t}>{t}</option>)}
              </select>
            </div>
            <div>
              <label className="text-[10px] uppercase font-bold text-muted-app mb-1 block">Program</label>
              <select value={auto.program} onChange={(e) => setAuto({ ...auto, program: e.target.value, semesters: [] })} className="input-base w-full text-sm">
                {programs.map((p) => <option key={p.code} value={p.shortForm || p.code}>{p.shortForm || p.code} — {p.name}</option>)}
              </select>
            </div>
          </div>

          <div>
            <label className="text-[10px] uppercase font-bold text-muted-app mb-1 block">Semester Selection</label>
            <div className="flex gap-2 mb-2">
              {[["ALL", "All Semesters"], ["ONE", "One Semester"], ["MULTI", "Multiple"]].map(([v, l]) => (
                <button key={v} type="button" onClick={() => setAuto({ ...auto, semesterMode: v, semesters: [] })}
                  className={`text-xs px-3 py-1.5 rounded-lg border ${auto.semesterMode === v ? "bg-blue-600 text-white border-blue-600" : "border-app text-app"}`}>{l}</button>
              ))}
            </div>
            {(auto.semesterMode === "ONE" || auto.semesterMode === "MULTI") && (
              <div className="flex flex-wrap gap-2">
                {semOptions.map((s) => (
                  <label key={s.value} className={`text-xs px-3 py-1.5 rounded-lg border cursor-pointer ${auto.semesters.includes(s.value) ? "bg-violet-600 text-white border-violet-600" : "border-app text-app"}`}>
                    <input type={auto.semesterMode === "ONE" ? "radio" : "checkbox"} name="autosem" className="hidden"
                      checked={auto.semesters.includes(s.value)}
                      onChange={() => auto.semesterMode === "ONE" ? setAuto({ ...auto, semesters: [s.value] }) : toggleSemester(s.value)} />
                    {s.label}
                  </label>
                ))}
                {semOptions.length === 0 && <span className="text-xs text-muted-app">No semesters for this program.</span>}
              </div>
            )}
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div><label className="text-[10px] uppercase font-bold text-muted-app mb-1 block">Start Date</label><input type="date" value={auto.startDate} onChange={(e) => setAuto({ ...auto, startDate: e.target.value })} className="input-base w-full text-sm" /></div>
            <div><label className="text-[10px] uppercase font-bold text-muted-app mb-1 block">Exam Duration (min)</label><input type="number" value={auto.durationMin} onChange={(e) => setAuto({ ...auto, durationMin: e.target.value })} className="input-base w-full text-sm" /></div>
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div><label className="text-[10px] uppercase font-bold text-muted-app mb-1 block">GAP Day(s)</label><input type="number" min="0" value={auto.gapDays} onChange={(e) => setAuto({ ...auto, gapDays: e.target.value })} className="input-base w-full text-sm" /></div>
            <div><label className="text-[10px] uppercase font-bold text-muted-app mb-1 block">Slots Per Day</label><select value={auto.slotsPerDay} onChange={(e) => setAuto({ ...auto, slotsPerDay: e.target.value })} className="input-base w-full text-sm">{[1, 2, 3].map((n) => <option key={n} value={n}>{n}</option>)}</select></div>
          </div>

          <p className="text-[11px] text-muted-app">Exams are conducted online — no room allocation is required. Each student and teacher will receive a personalized schedule when the date sheet is locked.</p>

          <div className="flex justify-end gap-2 pt-2">
            <button onClick={() => setShowAuto(false)} className="btn-secondary text-sm py-2 px-4">Cancel</button>
            <button onClick={runAutoGenerate} disabled={busy} className="btn-primary text-sm py-2 px-4 disabled:opacity-50">{busy ? "Generating…" : "Auto Generate"}</button>
          </div>
        </div>
      </Modal>

      {/* MANUAL MODAL */}
      <Modal open={showManual} onClose={() => setShowManual(false)} title="Manual Date Sheet" icon="Plus" maxWidth="max-w-2xl">
        <div className="space-y-3">
          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3">
            <div className="lg:col-span-2"><label className="text-[10px] uppercase font-bold text-muted-app mb-1 block">Title</label><input value={manual.title} onChange={(e) => setManual({ ...manual, title: e.target.value })} className="input-base w-full text-sm" placeholder="e.g. ADCS Semester 1 Final" /></div>
            <div><label className="text-[10px] uppercase font-bold text-muted-app mb-1 block">Exam Type</label><select value={manual.examType} onChange={(e) => setManual({ ...manual, examType: e.target.value })} className="input-base w-full text-sm">{EXAM_TYPES.map((t) => <option key={t} value={t}>{t}</option>)}</select></div>
            <div><label className="text-[10px] uppercase font-bold text-muted-app mb-1 block">Program</label><select value={manual.program} onChange={(e) => setManual({ ...manual, program: e.target.value, semester: "" })} className="input-base w-full text-sm"><option value="">—</option>{programs.map((p) => <option key={p.code} value={p.shortForm || p.code}>{p.shortForm || p.code}</option>)}</select></div>
          </div>
          <div className="grid sm:grid-cols-4 gap-3">
            <div><label className="text-[10px] uppercase font-bold text-muted-app mb-1 block">Semester</label><select value={manual.semester} onChange={(e) => setManual({ ...manual, semester: e.target.value })} className="input-base w-full text-sm"><option value="">—</option>{manualSemOptions.map((s) => <option key={s.value} value={s.value}>{s.label}</option>)}</select></div>
          </div>

          <div className="border border-app rounded-xl overflow-x-auto">
            <table className="w-full text-sm">
              <thead className="surface border-b border-app"><tr>
                {["Course Code", "Course Title", "Section", "Date", "Start", "End", ""].map((h) => <th key={h} className="px-2 py-2 text-left text-[10px] font-bold uppercase text-muted-app">{h}</th>)}
              </tr></thead>
              <tbody className="divide-y divide-app">
                {manualEntries.map((row, i) => (
                  <tr key={i}>
                    <td className="px-1 py-1"><input value={row.courseCode} onChange={(e) => updateManualRow(i, "courseCode", e.target.value)} className="input-base text-xs w-24" /></td>
                    <td className="px-1 py-1"><input value={row.courseTitle} onChange={(e) => updateManualRow(i, "courseTitle", e.target.value)} className="input-base text-xs w-32" /></td>
                    <td className="px-1 py-1"><input value={row.section} onChange={(e) => updateManualRow(i, "section", e.target.value)} className="input-base text-xs w-16" /></td>
                    <td className="px-1 py-1"><input type="date" value={row.date} onChange={(e) => updateManualRow(i, "date", e.target.value)} className="input-base text-xs w-32" /></td>
                    <td className="px-1 py-1"><input type="time" value={row.startTime} onChange={(e) => updateManualRow(i, "startTime", e.target.value)} className="input-base text-xs w-24" /></td>
                    <td className="px-1 py-1"><input type="time" value={row.endTime} onChange={(e) => updateManualRow(i, "endTime", e.target.value)} className="input-base text-xs w-24" /></td>
                    <td className="px-1 py-1">{manualEntries.length > 1 && <button onClick={() => removeManualRow(i)} className="p-1 text-rose-600"><Trash2 size={13} /></button>}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <button onClick={addManualRow} className="text-xs text-blue-600 font-bold inline-flex items-center gap-1"><Plus size={12} /> Add Row</button>

          <div className="flex justify-end gap-2 pt-2">
            <button onClick={() => setShowManual(false)} className="btn-secondary text-sm py-2 px-4">Cancel</button>
            <button onClick={saveManual} disabled={busy} className="btn-primary text-sm py-2 px-4 disabled:opacity-50">{busy ? "Saving…" : "Save Date Sheet"}</button>
          </div>
        </div>
      </Modal>
    </div>
  );
};

export default ExamDatesheets;
